#pragma once

struct RadioStation {
    const char* name;
    const char* url;
    const char* lang;
};

static const RadioStation stations[] = {

    // ── Confirmed working ────────────────────────────────────────────────────
    {"WDR EinsLive",    "http://www.wdr.de/wdrlive/media/einslive.m3u",              "DE"},

    // ── Various sources ──────────────────────────────────────────────────────
    {"Capital FM",      "http://vis.media-ice.musicradio.com/CapitalMP3",             "EN"},
    {"BBC Radio 1",     "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one",        "EN"},
    {"Radio Paradise",  "https://stream.radioparadise.com/mp3-192",                  "EN"},
    {"France Inter",    "https://icecast.radiofrance.fr/franceinter-midfi.mp3",      "FR"},
    {"Vesti FM",        "http://icecast.vgtrk.cdnvideo.ru/vestifm_mp3_192kbps",     "RU"},
    {"Record",          "http://radiorecord.hostingradio.ru/record96.aacp",          "RU"},
    {"RNE Radio 3",     "http://rne3-lp.rtveradio.cires21.com/rne3/rne3.mp3",       "ES"},
    {"Classical 102",   "http://tuner.classical102.com/listen.pls",                  "CL"},
    {"SomaFM Groove",   "https://somafm.com/groovesalad256.pls",                    "US"},

    // ── Top Radio (radio.pervii.com) ─────────────────────────────────────────
    {"TR Russian",      "http://radio.pervii.com/top_radio_russian.m3u",             "RU"},
    {"TR Top 40",       "http://radio.pervii.com/top_radio_top_40.m3u",              "40"},
    {"TR Pop",          "http://radio.pervii.com/top_radio_pop.m3u",                 "POP"},
    {"TR Rock",         "http://radio.pervii.com/top_radio_rock.m3u",                "ROK"},
    {"TR 60s",          "http://radio.pervii.com/top_radio_60s.m3u",                 "60s"},
    {"TR 70s",          "http://radio.pervii.com/top_radio_70s.m3u",                 "70s"},
    {"TR 80s",          "http://radio.pervii.com/top_radio_80s.m3u",                 "80s"},
    {"TR 90s",          "http://radio.pervii.com/top_radio_90s.m3u",                 "90s"},
    {"TR Acid Jazz",    "http://radio.pervii.com/top_radio_acid_jazz.m3u",           "AJZ"},
    {"TR African",      "http://radio.pervii.com/top_radio_african.m3u",             "AFR"},
    {"TR Alternative",  "http://radio.pervii.com/top_radio_alternative.m3u",         "ALT"},
    {"TR Ambient",      "http://radio.pervii.com/top_radio_ambient.m3u",             "AMB"},
    {"TR Americana",    "http://radio.pervii.com/top_radio_americana.m3u",           "AMR"},
    {"TR Anime",        "http://radio.pervii.com/top_radio_anime.m3u",               "ANI"},
    {"TR Arabic",       "http://radio.pervii.com/top_radio_arabic.m3u",              "AR"},
    {"TR Asian",        "http://radio.pervii.com/top_radio_asian.m3u",               "ASN"},
    {"TR Big Band",     "http://radio.pervii.com/top_radio_big_band.m3u",            "BB"},
    {"TR Bluegrass",    "http://radio.pervii.com/top_radio_bluegrass.m3u",           "BLG"},
    {"TR Blues",        "http://radio.pervii.com/top_radio_blues.m3u",               "BLU"},
    {"TR Breakbeat",    "http://radio.pervii.com/top_radio_breakbeat.m3u",           "BRK"},
    {"TR Chillout",     "http://radio.pervii.com/top_radio_chillout.m3u",            "CHL"},
    {"TR Christian",    "http://radio.pervii.com/top_radio_christian.m3u",           "CHR"},
    {"TR Classical",    "http://radio.pervii.com/top_radio_classical.m3u",           "CLS"},
    {"TR Club",         "http://radio.pervii.com/top_radio_club.m3u",                "CLB"},
    {"TR College",      "http://radio.pervii.com/top_radio_college.m3u",             "CLG"},
    {"TR Comedy",       "http://radio.pervii.com/top_radio_comedy.m3u",              "COM"},
    {"TR Country",      "http://radio.pervii.com/top_radio_country.m3u",             "CTR"},
    {"TR Dance",        "http://radio.pervii.com/top_radio_dance.m3u",               "DNC"},
    {"TR Deutsch",      "http://radio.pervii.com/top_radio_deutsch.m3u",             "DE"},
    {"TR Disco",        "http://radio.pervii.com/top_radio_disco.m3u",               "DSC"},
    {"TR Discofox",     "http://radio.pervii.com/top_radio_discofox.m3u",            "DFX"},
    {"TR Downtempo",    "http://radio.pervii.com/top_radio_downtempo.m3u",           "DWN"},
    {"TR Drum&Bass",    "http://radio.pervii.com/top_radio_drum_and_bass.m3u",       "DB"},
    {"TR EasyListen",   "http://radio.pervii.com/top_radio_easy_listening.m3u",      "EZ"},
    {"TR EBM",          "http://radio.pervii.com/top_radio_ebm.m3u",                 "EBM"},
    {"TR Electronic",   "http://radio.pervii.com/top_radio_electronic.m3u",          "EL"},
    {"TR Eurodance",    "http://radio.pervii.com/top_radio_eurodance.m3u",           "EUR"},
    {"TR Film",         "http://radio.pervii.com/top_radio_film.m3u",                "FLM"},
    {"TR Folk",         "http://radio.pervii.com/top_radio_folk.m3u",                "FLK"},
    {"TR France",       "http://radio.pervii.com/top_radio_france.m3u",              "FR"},
    {"TR Funk",         "http://radio.pervii.com/top_radio_funk.m3u",                "FNK"},
    {"TR Gay",          "http://radio.pervii.com/top_radio_gay.m3u",                 "GAY"},
    {"TR Goa",          "http://radio.pervii.com/top_radio_goa.m3u",                 "GOA"},
    {"TR Gospel",       "http://radio.pervii.com/top_radio_gospel.m3u",              "GSP"},
    {"TR Gothic",       "http://radio.pervii.com/top_radio_gothic.m3u",              "GTH"},
    {"TR Greek",        "http://radio.pervii.com/top_radio_greek.m3u",               "GRK"},
    {"TR Hardcore",     "http://radio.pervii.com/top_radio_hardcore.m3u",            "HXC"},
    {"TR Hard Rock",    "http://radio.pervii.com/top_radio_hardrock.m3u",            "HRK"},
    {"TR Hip Hop",      "http://radio.pervii.com/top_radio_hip_hop.m3u",             "HHP"},
    {"TR House",        "http://radio.pervii.com/top_radio_house.m3u",               "HSE"},
    {"TR India",        "http://radio.pervii.com/top_radio_india.m3u",               "IND"},
    {"TR Indie",        "http://radio.pervii.com/top_radio_indie.m3u",               "IDI"},
    {"TR Industrial",   "http://radio.pervii.com/top_radio_industrial.m3u",          "IDS"},
    {"TR Instrumental", "http://radio.pervii.com/top_radio_instrumental.m3u",        "INS"},
    {"TR Italian",      "http://radio.pervii.com/top_radio_italian.m3u",             "IT"},
    {"TR Jazz",         "http://radio.pervii.com/top_radio_jazz.m3u",                "JZZ"},
    {"TR J-Pop",        "http://radio.pervii.com/top_radio_jpop.m3u",                "JPP"},
    {"TR Jungle",       "http://radio.pervii.com/top_radio_jungle.m3u",              "JNG"},
    {"TR Latin",        "http://radio.pervii.com/top_radio_latin.m3u",               "LAT"},
    {"TR Lounge",       "http://radio.pervii.com/top_radio_lounge.m3u",              "LNG"},
    {"TR Metal",        "http://radio.pervii.com/top_radio_metal.m3u",               "MTL"},
    {"TR Mixed",        "http://radio.pervii.com/top_radio_mixed.m3u",               "MXD"},
    {"TR Musical",      "http://radio.pervii.com/top_radio_musical.m3u",             "MSC"},
    {"TR Oldies",       "http://radio.pervii.com/top_radio_oldies.m3u",              "OLD"},
    {"TR Opera",        "http://radio.pervii.com/top_radio_opera.m3u",               "OPR"},
    {"TR Polish",       "http://radio.pervii.com/top_radio_polish.m3u",              "PL"},
    {"TR Polka",        "http://radio.pervii.com/top_radio_polka.m3u",               "PLK"},
    {"TR Portugal",     "http://radio.pervii.com/top_radio_portugal.m3u",            "PT"},
    {"TR Progressive",  "http://radio.pervii.com/top_radio_progressive.m3u",         "PRG"},
    {"TR Punk",         "http://radio.pervii.com/top_radio_punk.m3u",                "PNK"},
    {"TR Quran",        "http://radio.pervii.com/top_radio_quran.m3u",               "QRN"},
    {"TR Rap",          "http://radio.pervii.com/top_radio_rap.m3u",                 "RAP"},
    {"TR Reggae",       "http://radio.pervii.com/top_radio_reggae.m3u",              "REG"},
    {"TR Retro",        "http://radio.pervii.com/top_radio_retro.m3u",               "RET"},
    {"TR R&B",          "http://radio.pervii.com/top_radio_rnb.m3u",                 "RNB"},
    {"TR Romanian",     "http://radio.pervii.com/top_radio_romanian.m3u",            "RO"},
    {"TR Salsa",        "http://radio.pervii.com/top_radio_salsa.m3u",               "SLS"},
    {"TR Schlager",     "http://radio.pervii.com/top_radio_schlager.m3u",            "SCH"},
    {"TR Ska",          "http://radio.pervii.com/top_radio_ska.m3u",                 "SKA"},
    {"TR Smooth Jazz",  "http://radio.pervii.com/top_radio_smooth_jazz.m3u",         "SJZ"},
    {"TR Soul",         "http://radio.pervii.com/top_radio_soul.m3u",                "SOL"},
    {"TR Soundtrack",   "http://radio.pervii.com/top_radio_soundtrack.m3u",          "STK"},
    {"TR Spain",        "http://radio.pervii.com/top_radio_spain.m3u",               "ES"},
    {"TR Spiritual",    "http://radio.pervii.com/top_radio_spiritual.m3u",           "SPR"},
    {"TR Sport",        "http://radio.pervii.com/top_radio_sport.m3u",               "SPT"},
    {"TR Swing",        "http://radio.pervii.com/top_radio_swing.m3u",               "SWG"},
    {"TR Symphonic",    "http://radio.pervii.com/top_radio_symphonic.m3u",           "SYM"},
    {"TR Talk",         "http://radio.pervii.com/top_radio_talk.m3u",                "TLK"},
    {"TR Techno",       "http://radio.pervii.com/top_radio_techno.m3u",              "TCH"},
    {"TR Trance",       "http://radio.pervii.com/top_radio_trance.m3u",              "TRN"},
    {"TR Turkish",      "http://radio.pervii.com/top_radio_turk.m3u",               "TUR"},
    {"TR Urban",        "http://radio.pervii.com/top_radio_urban.m3u",               "URB"},
    {"TR USA",          "http://radio.pervii.com/top_radio_usa.m3u",                 "USA"},
    {"TR Various",      "http://radio.pervii.com/top_radio_various.m3u",             "VAR"},
    {"TR Wave",         "http://radio.pervii.com/top_radio_wave.m3u",                "WAV"},
    {"TR World",        "http://radio.pervii.com/top_radio_world.m3u",               "WLD"},
};

static const int STATION_COUNT = sizeof(stations) / sizeof(stations[0]);
